import happyx


translatable:
  "Welcome to my CV":
    "ru" -> "Добро пожаловать в мое резюме"
    "ko" -> "나의 이력서에 오신 것을 환영합니다"
    "ja" -> "私の履歴書へようこそ"
    "es" -> "Bienvenido a mi CV"
    "fr" -> "Bienvenue dans mon CV"
    "de" -> "Willkommen in meinem Lebenslauf"
    "it" -> "Benvenuto nel mio CV"
    "zh" -> "欢迎来到我的简历"
    "pt" -> "Bem-vindo ao meu CV"
    "ar" -> "مرحبًا بك في سيرتي الذاتية"
  "CV":
    "ru" -> "Резюме"
    "ko" -> "이력서"
    "ja" -> "履歴書"
    "es" -> "CV"
    "fr" -> "CV"
    "de" -> "Lebenslauf"
    "it" -> "CV"
    "zh" -> "简历"
    "pt" -> "CV"
    "ar" -> "السيرة الذاتية"
  "My projects:":
    "ru" -> "Мои проекты:"
    "ko" -> "내 프로젝트:"
    "ja" -> "私のプロジェクト:"
    "es" -> "Mis proyectos:"
    "fr" -> "Mes projets :"
    "de" -> "Meine Projekte:"
    "it" -> "I miei progetti:"
    "zh" -> "我的项目："
    "pt" -> "Meus projetos:"
    "ar" -> "مشاريعي:"
  "My skills:":
    "ru" -> "Мои навыки:"
    "ko" -> "나의 기술:"
    "ja" -> "私のスキル:"
    "es" -> "Mis habilidades:"
    "fr" -> "Mes compétences :"
    "de" -> "Meine Fähigkeiten:"
    "it" -> "Le mie competenze:"
    "zh" -> "我的技能："
    "pt" -> "Minhas habilidades:"
    "ar" -> "مهاراتي:"
  "Contact me:":
    "ru" -> "Связаться со мной:"
    "ko" -> "연락처:"
    "ja" -> "お問い合わせ:"
    "es" -> "Contáctame:"
    "fr" -> "Contactez-moi :"
    "de" -> "Kontaktiere mich:"
    "it" -> "Contattami:"
    "zh" -> "联系我："
    "pt" -> "Contate-me:"
    "ar" -> "اتصل بي:"
  "Programming languages":
    "ru" -> "Языки программирования"
    "ko" -> "프로그래밍 언어"
    "ja" -> "プログラミング言語"
    "es" -> "Lenguajes de programación"
    "fr" -> "Langages de programmation"
    "de" -> "Programmiersprachen"
    "it" -> "Linguaggi di programmazione"
    "zh" -> "编程语言"
    "pt" -> "Linguagens de programação"
    "ar" -> "لغات البرمجة"
  "Web frameworks":
    "ru" -> "Веб-фреймворки"
    "ko" -> "웹 프레임워크"
    "ja" -> "ウェブフレームワーク"
    "es" -> "Frameworks web"
    "fr" -> "Frameworks web"
    "de" -> "Web-Frameworks"
    "it" -> "Framework Web"
    "zh" -> "Web框架"
    "pt" -> "Frameworks web"
    "ar" -> "أطر الويب"
  "Databases":
    "ru" -> "Базы данных"
    "ko" -> "데이터베이스"
    "ja" -> "データベース"
    "es" -> "Bases de datos"
    "fr" -> "Bases de données"
    "de" -> "Datenbanken"
    "it" -> "Database"
    "zh" -> "数据库"
    "pt" -> "Bancos de dados"
    "ar" -> "قواعد البيانات"
  "Other":
    "ru" -> "Прочее"
    "ko" -> "기타"
    "ja" -> "その他"
    "es" -> "Otros"
    "fr" -> "Autre"
    "de" -> "Andere"
    "it" -> "Altro"
    "zh" -> "其他"
    "pt" -> "Outro"
    "ar" -> "آخر"
